//! Port of the netCDF-Java code tables grib2json reads through:
//! `ucar.grib.grib2.Grib2Tables`, `ucar.grib.grib2.ParameterTable`,
//! `ucar.grib.grib1.Grib1Tables` and the `*Name()` accessors on the indicator
//! and identification sections.
//!
//! **These entries were extracted from the Java classes, not transcribed from
//! the WMO manual.** A probe on the classpath of the Java build called each
//! accessor over its code range and printed what came back; this file is that
//! output. That matters because netCDF-Java's spellings are its own -- it says
//! `"Rotated_Latitude_Longitude"` where the manual says "rotated latitude
//! longitude", and `"Earth represent by WGS84"` with the grammar slip intact.
//! Any of those differences would show up in a `--names` header.
//!
//! Each fallback is netCDF-Java's own, including the ones that embed the code:
//! `"Unknown projection42"`, `"Unknown=99"`, `"UnknownParameter_D0_C2_99"`.

/// netCDF-Java's plain fallback, used by the tables that have no formatted one.
const UNKNOWN: &str = "Unknown";

/// `Grib2IndicatorSection.getDisciplineName()`.
///
/// Not the same table as [`parameter_table_discipline_name`], despite the name.
/// The indicator section spells discipline 0 `"Meteorological products"` with a
/// space; `ParameterTable` spells the same code `"Meteorological_products"` with
/// an underscore. `GribRecordWriter.writeIndicator` reads the first,
/// `OscarRecordWriter.writeIndicator` reads the second, so both are kept and
/// neither is allowed to stand in for the other.
pub fn discipline_name(discipline: i32) -> String {
    match discipline {
        0 => "Meteorological products",
        1 => "Hydrological products",
        2 => "Land surface products",
        3 => "Space products",
        10 => "Oceanographic products",
        _ => UNKNOWN,
    }
    .to_string()
}

/// `ParameterTable.getDisciplineName(int)` -- the underscored spelling.
pub fn parameter_table_discipline_name(discipline: i32) -> String {
    match discipline {
        0 => "Meteorological_products".to_string(),
        1 => "Hydrological_products".to_string(),
        2 => "Land_surface_products".to_string(),
        3 => "Space_Products".to_string(),
        10 => "Oceanographic_products".to_string(),
        n => format!("UnknownDiscipline_{n}"),
    }
}

/// `Grib2IdentificationSection.getSignificanceOfRTName()`.
pub fn significance_of_rt_name(code: i32) -> &'static str {
    match code {
        0 => "Analysis",
        1 => "Start of forecast",
        2 => "Verifying time of forecast",
        3 => "Observation time",
        _ => UNKNOWN,
    }
}

/// `Grib2IdentificationSection.getProductStatusName()`.
pub fn product_status_name(code: i32) -> &'static str {
    match code {
        0 => "Operational products",
        1 => "Operational test products",
        2 => "Research products",
        3 => "Re-analysis products",
        _ => UNKNOWN,
    }
}

/// `Grib2IdentificationSection.getProductTypeName()`.
pub fn product_type_name(code: i32) -> &'static str {
    match code {
        0 => "Analysis products",
        1 => "Forecast products",
        2 => "Analysis and forecast products",
        3 => "Control forecast products",
        4 => "Perturbed forecast products",
        5 => "Control and perturbed forecast products",
        6 => "Processed satellite observations",
        7 => "Processed radar observations",
        _ => UNKNOWN,
    }
}

/// `Grib1Tables.getCenter_idName(int)`.
pub fn center_id_name(center: i32) -> &'static str {
    match center {
        0 => "WMO Secretariat",
        1 => "Melbourne(WMC)",
        2 => "Melbourne(WMC)",
        3 => "Melbourne(WMC)",
        4 => "Moscow(WMC)",
        5 => "Moscow(WMC)",
        6 => "Moscow(WMC)",
        7 => "US National Weather Service - NCEP(WMC)",
        8 => "US National Weather Service - NWSTG(WMC)",
        9 => "US National Weather Service - Other(WMC)",
        10 => "Cairo (RSMC/RAFC)",
        11 => "Cairo (RSMC/RAFC)",
        12 => "Dakar (RSMC/RAFC)",
        13 => "Dakar (RSMC/RAFC)",
        14 => "Nairobi (RSMC/RAFC)",
        15 => "Nairobi (RSMC/RAFC)",
        16 => "Casablanca (RSMC)",
        17 => "Tunis (RSMC)",
        18 => "Tunis Casablanca (RSMC)",
        19 => "Tunis Casablanca (RSMC)",
        20 => "Las Palmas (RAFC)",
        21 => "Algiers (RSMC)",
        22 => "ACMAD",
        23 => "Mozambique (NMC)",
        24 => "Pretoria (RSMC)",
        25 => "La Reunion (RSMC)",
        26 => "Khabarovsk (RSMC)",
        27 => "Khabarovsk (RSMC)",
        28 => "New Delhi (RSMC/RAFC)",
        29 => "New Delhi (RSMC/RAFC)",
        30 => "Novosibirsk (RSMC)",
        31 => "Novosibirsk (RSMC)",
        32 => "Tashkent (RSMC)",
        33 => "Jeddah (RSMC)",
        34 => "Japan Meteorological Agency - Tokyo (RSMC), ",
        35 => "Japan Meteorological Agency - Tokyo (RSMC), ",
        36 => "Bangkok",
        37 => "Ulan Bator",
        38 => "Beijing (RSMC)",
        39 => "Beijing (RSMC)",
        40 => "Seoul",
        41 => "Buenos Aires (RSMC/RAFC)",
        42 => "Buenos Aires (RSMC/RAFC)",
        43 => "Brasilia (RSMC/RAFC)",
        44 => "Brasilia (RSMC/RAFC)",
        45 => "Santiago",
        46 => "Brazilian Space Agency - INPE",
        47 => "Columbia (NMC)",
        48 => "Ecuador (NMC)",
        49 => "Peru (NMC)",
        50 => "Venezuela (NMC)",
        51 => "Miami (RSMC/RAFC)",
        52 => "Tropical Prediction Center(NHC), Miami (RSMC)",
        53 => "Canadian Meteorological Service - Montreal (RSMC)",
        54 => "Canadian Meteorological Service - Montreal (RSMC)",
        55 => "San Francisco",
        56 => "ARINC Center",
        57 => "U.S. Air Force - Global Weather Center",
        58 => "U.S. Navy Fleet Numerical Meteorology and Oceanography Center",
        59 => "The NOAA Forecast Systems Laboratory",
        60 => "National Centre for Atmospheric Research (NCAR), Boulder, CO",
        61 => "Service ARGOS - Landover, MD, USA",
        62 => "US Naval Oceanographic Office",
        64 => "Honolulu",
        65 => "Darwin (RSMC)",
        66 => "Darwin (RSMC)",
        67 => "Melbourne (RSMC)",
        69 => "Wellington (RSMC/RAFC)",
        70 => "Wellington (RSMC/RAFC)",
        71 => "Nadi (RSMC)",
        72 => "Singapore",
        73 => "Malaysia (NMC)",
        74 => "U.K. Met Office - Exeter (RSMC)",
        75 => "U.K. Met Office - Exeter (RSMC)",
        76 => "Moscow (RSMC/RAFC)",
        78 => "Offenbach (RSMC)",
        79 => "Offenbach (RSMC)",
        80 => "Rome (RSMC)",
        81 => "Rome (RSMC)",
        82 => "Norrkoping",
        83 => "Norrkoping",
        84 => "French Weather Service - Toulouse (RSMC)",
        85 => "French Weather Service - Toulouse (RSMC)",
        86 => "Helsinki",
        87 => "Belgrade",
        88 => "Oslo",
        89 => "Prague",
        90 => "Episkopi",
        91 => "Ankara",
        92 => "Frankfurt/Main (RAFC)",
        93 => "London (WAFC)",
        94 => "Copenhagen",
        95 => "Rota",
        96 => "Athens",
        97 => "European Space Agency (ESA)",
        98 => "European Center for Medium-Range Weather Forecasts (RSMC)",
        99 => "De Bilt, Netherlands",
        100 => "Brazzaville",
        101 => "Abidjan",
        102 => "Libyan Arab Jamahiriya (NMC)",
        103 => "Madagascar (NMC)",
        104 => "Mauritius (NMC)",
        105 => "Niger (NMC)",
        106 => "Seychelles (NMC)",
        107 => "Uganda (NMC)",
        108 => "Tanzania (NMC)",
        109 => "Zimbabwe (NMC)",
        110 => "Hong-Kong",
        111 => "Afghanistan (NMC)",
        112 => "Bahrain (NMC)",
        113 => "Bangladesh (NMC)",
        114 => "Bhutan (NMC)",
        115 => "Cambodia (NMC)",
        116 => "Democratic People's Republic of Korea (NMC)",
        117 => "Islamic Republic of Iran (NMC)",
        118 => "Iraq (NMC)",
        119 => "Kazakhstan (NMC)",
        120 => "Kuwait (NMC)",
        121 => "Kyrgyz Republic (NMC)",
        122 => "Lao People's Democratic Republic (NMC)",
        123 => "Macao, China",
        124 => "Maldives (NMC)",
        125 => "Myanmar (NMC)",
        126 => "Nepal (NMC)",
        127 => "Oman (NMC)",
        128 => "Pakistan (NMC)",
        129 => "Qatar (NMC)",
        130 => "Republic of Yemen (NMC)",
        131 => "Sri Lanka (NMC)",
        132 => "Tajikistan (NMC)",
        133 => "Turkmenistan (NMC)",
        134 => "United Arab Emirates (NMC)",
        135 => "Uzbekistan (NMC)",
        136 => "Socialist Republic of Viet Nam (NMC)",
        140 => "Bolivia (NMC)",
        141 => "Guyana (NMC)",
        142 => "Paraguay (NMC)",
        143 => "Suriname (NMC)",
        144 => "Uruguay (NMC)",
        145 => "French Guyana",
        146 => "Brazilian Navy Hydrographic Center",
        150 => "Antigua and Barbuda (NMC)",
        151 => "Bahamas (NMC)",
        152 => "Barbados (NMC)",
        153 => "Belize (NMC)",
        154 => "British Caribbean Territories Center",
        155 => "San Jose",
        156 => "Cuba (NMC)",
        157 => "Dominica (NMC)",
        158 => "Dominican Republic (NMC)",
        159 => "El Salvador (NMC)",
        160 => "US NOAA/NESDIS",
        161 => "US NOAA Office of Oceanic and Atmospheric Research",
        162 => "Guatemala (NMC)",
        163 => "Haiti (NMC)",
        164 => "Honduras (NMC)",
        165 => "Jamaica (NMC)",
        166 => "Mexico",
        167 => "Netherlands Antilles and Aruba (NMC)",
        168 => "Nicaragua (NMC)",
        169 => "Panama (NMC)",
        170 => "Saint Lucia (NMC)",
        171 => "Trinidad and Tobago (NMC)",
        172 => "French Departments",
        190 => "Cook Islands (NMC)",
        191 => "French Polynesia (NMC)",
        192 => "Tonga (NMC)",
        193 => "Vanuatu (NMC)",
        194 => "Brunei (NMC)",
        195 => "Indonesia (NMC)",
        196 => "Kiribati (NMC)",
        197 => "Federated States of Micronesia (NMC)",
        198 => "New Caledonia (NMC)",
        199 => "Niue",
        200 => "Papua New Guinea (NMC)",
        201 => "Philippines (NMC)",
        202 => "Samoa (NMC)",
        203 => "Solomon Islands (NMC)",
        210 => "Frascati (ESA/ESRIN)",
        211 => "Lanion",
        212 => "Lisboa",
        213 => "Reykjavik",
        214 => "Madrid",
        215 => "Zurich",
        216 => "Service ARGOS - Toulouse, FR",
        217 => "Bratislava",
        218 => "Budapest",
        219 => "Ljubljana",
        220 => "Warsaw",
        221 => "Zagreb",
        222 => "Albania (NMC)",
        223 => "Armenia (NMC)",
        224 => "Austria (NMC)",
        225 => "Azerbaijan (NMC)",
        226 => "Belarus (NMC)",
        227 => "Belgium (NMC)",
        228 => "Bosnia and Herzegovina (NMC)",
        229 => "Bulgaria (NMC)",
        230 => "Cyprus (NMC)",
        231 => "Estonia (NMC)",
        232 => "Georgia (NMC)",
        233 => "Dublin",
        234 => "Israel (NMC)",
        235 => "Jordan (NMC)",
        236 => "Latvia (NMC)",
        237 => "Lebanon (NMC)",
        238 => "Lithuania (NMC)",
        239 => "Luxembourg",
        240 => "Malta (NMC)",
        241 => "Monaco",
        242 => "Romania (NMC)",
        243 => "Syrian Arab Republic (NMC)",
        244 => "The former Yugoslav Republic of Macedonia (NMC)",
        245 => "Ukraine (NMC)",
        246 => "Republic of Moldova",
        254 => "EUMETSAT Operation Centre",
        _ => UNKNOWN,
    }
}

/// `Grib2Tables.codeTable3_1(int)` -- grid definition template.
pub fn code_table3_1(template: i32) -> String {
    (match template {
        0 => "Latitude_Longitude",
        1 => "Rotated_Latitude_Longitude",
        2 => "Stretched_Latitude_Longitude",
        3 => "Rotated_and_Stretched_Latitude_Longitude",
        10 => "Mercator",
        20 => "Polar_Stereographic",
        30 => "Lambert_Conformal",
        31 => "Albers_Equal_Area",
        40 => "Gaussian_Latitude_Longitude",
        41 => "Rotated_Gaussian_Latitude_Longitude",
        42 => "Stretched_Gaussian Latitude_Longitude",
        43 => "Rotated_and_Stretched_Gaussian_Latitude_Longitude",
        50 => "Spherical_Harmonic_Coefficients",
        51 => "Rotated_Spherical_Harmonic_Coefficients",
        52 => "Stretched_Spherical_Harmonic_Coefficients",
        53 => "Rotated_and_Stretched_Spherical_Harmonic_Coefficients",
        90 => "Space_View_Perspective_or_Orthographic",
        100 => "Triangular_Grid_Based_on_an_Icosahedron",
        110 => "Equatorial_Azimuthal_Equidistant",
        120 => "Azimuth_Range",
        204 => "Curvilinear_Orthogonal",
        n => return format!("Unknown projection{n}"),
    })
    .to_string()
}

/// `Grib2Tables.codeTable3_2(int)` -- shape of the earth.
pub fn code_table3_2(shape: i32) -> &'static str {
    match shape {
        0 => "Earth spherical with radius = 6,367,470 m",
        1 => "Earth spherical with radius specified by producer in m",
        2 => "Earth oblate spheroid with major axis = 6,378,160 m and minor axis = 6,356,775 m",
        3 => "Earth oblate spheroid with axes specified by producer in m",
        4 => "Earth oblate spheroid with major axis = 6,378,137.0 m and minor axis = 6,356,752.314 m",
        5 => "Earth represent by WGS84",
        6 => "Earth spherical with radius of 6,371,229.0 m",
        7 => "Earth oblate spheroid with axes specified by producer in m",
        8 => "Earth spherical with radius of 6,371,200.0 m, represent by WGS84",
        _ => "Unknown Earth Shape",
    }
}

/// `Grib2Tables.codeTable4_0(int)` -- product definition template.
pub fn code_table4_0(template: i32) -> &'static str {
    match template {
        0 => "Analysis/forecast at horizontal level/layer at a point in time",
        1 => "Individual ensemble forecast at a point in time",
        2 => "Derived forecast on all ensemble members at a point in time",
        3 => "Derived forecasts on cluster of ensemble members over rectangular area at a point in time",
        4 => "Derived forecasts on cluster of ensemble members over circular area at a point in time",
        5 => "Probability forecasts at a horizontal level at a point in time",
        6 => "Percentile forecasts at a horizontal level at a point in time",
        7 => "Analysis or forecast error at a horizontal level at a point in time",
        8 => "Average, accumulation, extreme values or other statistically processed value at a horizontal level in a time interval",
        9 => "Probability forecasts at a horizontal level or in a horizontal layer in a time interval",
        10 => "Percentile forecasts at a horizontal level or in a horizontal layer in a time interval",
        11 => "Individual ensemble forecast in a time interval",
        12 => "Derived forecast on all ensemble members in a time interval",
        13 => "Derived forecasts on cluster of ensemble members over rectangular area  in a time interval",
        14 => "Derived forecasts on cluster of ensemble members over circular area  in a time interval",
        15 => "Average, accumulation, extreme values or other statistically-processed values over a spatial area at a horizontal level or in a horizontal layer at a point in time.",
        20 => "Radar product",
        30 => "Satellite product",
        31 => "Satellite product",
        40 => "Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for atmospheric chemical constituents.",
        41 => "Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for atmospheric chemical constituents.",
        42 => "Average, accumulation, and/or extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for atmospheric chemical constituents",
        43 => "Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval for atmospheric chemical constituents.",
        254 => "CCITT IA5 character string",
        _ => UNKNOWN,
    }
}

/// `Grib2Tables.codeTable4_3(int)` -- type of generating process.
pub fn code_table4_3(code: i32) -> &'static str {
    match code {
        0 => "Analysis",
        1 => "Initialization",
        2 => "Forecast",
        3 => "Bias Corrected Forecast",
        4 => "Ensemble Forecast",
        5 => "Probability Forecast",
        6 => "Forecast Error",
        7 => "Analysis Error",
        8 => "Observation",
        9 => "Climatological",
        10 => "Probability-Weighted Forecast",
        192 => "Forecast Confidence Indicator",
        193 => "Bias Corrected Ensemble Forecast",
        255 => "Missing",
        _ => UNKNOWN,
    }
}

/// `Grib2Tables.codeTable4_5(int)` -- fixed surface type.
pub fn code_table4_5(code: i32) -> String {
    (match code {
        1 => "Ground or water surface",
        2 => "Cloud base level",
        3 => "Level of cloud tops",
        4 => "Level of 0o C isotherm",
        5 => "Level of adiabatic condensation lifted from the surface",
        6 => "Maximum wind level",
        7 => "Tropopause",
        8 => "Nominal top of the atmosphere",
        9 => "Sea bottom",
        10 => "Entire Atmosphere",
        11 => "Cumulonimbus Base",
        12 => "Cumulonimbus Top",
        20 => "Isothermal level",
        100 => "Isobaric surface",
        101 => "Mean sea level",
        102 => "Specific altitude above mean sea level",
        103 => "Specified height level above ground",
        104 => "Sigma level",
        105 => "Hybrid level",
        106 => "Depth below land surface",
        107 => "Isentropic 'theta' level",
        108 => "Level at specified pressure difference from ground to level",
        109 => "Potential vorticity surface",
        111 => "Eta level",
        117 => "Mixed layer depth",
        160 => "Depth below sea level",
        200 => "Entire atmosphere layer",
        201 => "Entire ocean layer",
        204 => "Highest tropospheric freezing level",
        206 => "Grid scale cloud bottom level",
        207 => "Grid scale cloud top level",
        209 => "Boundary layer cloud bottom level",
        210 => "Boundary layer cloud top level",
        211 => "Boundary layer cloud layer",
        212 => "Low cloud bottom level",
        213 => "Low cloud top level",
        214 => "Low cloud layer",
        215 => "Cloud ceiling",
        220 => "Planetary Boundary Layer",
        221 => "Layer Between Two Hybrid Levels",
        222 => "Middle cloud bottom level",
        223 => "Middle cloud top level",
        224 => "Middle cloud layer",
        232 => "High cloud bottom level",
        233 => "High cloud top level",
        234 => "High cloud layer",
        235 => "Ocean isotherm level",
        236 => "Layer between two depths below ocean surface",
        237 => "Bottom of ocean mixed layer",
        238 => "Bottom of ocean isothermal layer",
        239 => "Layer Ocean Surface and 26C Ocean Isothermal Level",
        240 => "Ocean Mixed Layer",
        241 => "Ordered Sequence of Data",
        242 => "Convective cloud bottom level",
        243 => "Convective cloud top level",
        244 => "Convective cloud layer",
        245 => "Lowest level of the wet bulb zero",
        246 => "Maximum equivalent potential temperature level",
        247 => "Equilibrium level",
        248 => "Shallow convective cloud bottom level",
        249 => "Shallow convective cloud top level",
        251 => "Deep convective cloud bottom level",
        252 => "Deep convective cloud top level",
        253 => "Lowest bottom level of supercooled liquid water layer",
        254 => "Highest top level of supercooled liquid water layer",
        255 => "Missing",
        n => return format!("Unknown={n}"),
    })
    .to_string()
}

/// `ParameterTable.getCategoryName(discipline, category)`.
pub fn category_name(discipline: i32, category: i32) -> String {
    (match (discipline, category) {
        (0, 0) => "Temperature",
        (0, 1) => "Moisture",
        (0, 2) => "Momentum",
        (0, 3) => "Mass",
        (0, 4) => "Short-wave_Radiation",
        (0, 5) => "Long-wave_Radiation",
        (0, 6) => "Cloud",
        (0, 7) => "Thermodynamic_Stability_indices",
        (0, 13) => "Aerosols",
        (0, 14) => "Trace_gases",
        (0, 15) => "Radar",
        (0, 16) => "Forecast_Radar_Imagery",
        (0, 17) => "Electro-dynamics",
        (0, 18) => "Nuclear_and_radiology",
        (0, 19) => "Physical_atmospheric_properties",
        (0, 20) => "Atmospheric_chemical_constituents",
        (1, 0) => "Hydrology",
        (1, 1) => "Hydrology_probabilities",
        (2, 0) => "Vegetation_and_Biomass",
        (2, 3) => "Soil_Products",
        (3, 0) => "Image_format_products",
        (3, 1) => "Quantitative_products",
        (4, 0) => "UnknownDiscipline_4_Category_0",
        (4, 1) => "UnknownDiscipline_4_Category_1",
        (4, 2) => "UnknownDiscipline_4_Category_2",
        (4, 3) => "UnknownDiscipline_4_Category_3",
        (4, 4) => "UnknownDiscipline_4_Category_4",
        (4, 5) => "UnknownDiscipline_4_Category_5",
        (4, 6) => "UnknownDiscipline_4_Category_6",
        (4, 7) => "UnknownDiscipline_4_Category_7",
        (4, 8) => "UnknownDiscipline_4_Category_8",
        (4, 9) => "UnknownDiscipline_4_Category_9",
        (4, 10) => "UnknownDiscipline_4_Category_10",
        (4, 11) => "UnknownDiscipline_4_Category_11",
        (4, 12) => "UnknownDiscipline_4_Category_12",
        (4, 13) => "UnknownDiscipline_4_Category_13",
        (4, 14) => "UnknownDiscipline_4_Category_14",
        (4, 15) => "UnknownDiscipline_4_Category_15",
        (4, 16) => "UnknownDiscipline_4_Category_16",
        (4, 17) => "UnknownDiscipline_4_Category_17",
        (4, 18) => "UnknownDiscipline_4_Category_18",
        (4, 19) => "UnknownDiscipline_4_Category_19",
        (4, 20) => "UnknownDiscipline_4_Category_20",
        (4, 21) => "UnknownDiscipline_4_Category_21",
        (4, 22) => "UnknownDiscipline_4_Category_22",
        (4, 23) => "UnknownDiscipline_4_Category_23",
        (4, 24) => "UnknownDiscipline_4_Category_24",
        (4, 25) => "UnknownDiscipline_4_Category_25",
        (4, 26) => "UnknownDiscipline_4_Category_26",
        (4, 27) => "UnknownDiscipline_4_Category_27",
        (4, 28) => "UnknownDiscipline_4_Category_28",
        (4, 29) => "UnknownDiscipline_4_Category_29",
        (4, 30) => "UnknownDiscipline_4_Category_30",
        (5, 0) => "UnknownDiscipline_5_Category_0",
        (5, 1) => "UnknownDiscipline_5_Category_1",
        (5, 2) => "UnknownDiscipline_5_Category_2",
        (5, 3) => "UnknownDiscipline_5_Category_3",
        (5, 4) => "UnknownDiscipline_5_Category_4",
        (5, 5) => "UnknownDiscipline_5_Category_5",
        (5, 6) => "UnknownDiscipline_5_Category_6",
        (5, 7) => "UnknownDiscipline_5_Category_7",
        (5, 8) => "UnknownDiscipline_5_Category_8",
        (5, 9) => "UnknownDiscipline_5_Category_9",
        (5, 10) => "UnknownDiscipline_5_Category_10",
        (5, 11) => "UnknownDiscipline_5_Category_11",
        (5, 12) => "UnknownDiscipline_5_Category_12",
        (5, 13) => "UnknownDiscipline_5_Category_13",
        (5, 14) => "UnknownDiscipline_5_Category_14",
        (5, 15) => "UnknownDiscipline_5_Category_15",
        (5, 16) => "UnknownDiscipline_5_Category_16",
        (5, 17) => "UnknownDiscipline_5_Category_17",
        (5, 18) => "UnknownDiscipline_5_Category_18",
        (5, 19) => "UnknownDiscipline_5_Category_19",
        (5, 20) => "UnknownDiscipline_5_Category_20",
        (5, 21) => "UnknownDiscipline_5_Category_21",
        (5, 22) => "UnknownDiscipline_5_Category_22",
        (5, 23) => "UnknownDiscipline_5_Category_23",
        (5, 24) => "UnknownDiscipline_5_Category_24",
        (5, 25) => "UnknownDiscipline_5_Category_25",
        (5, 26) => "UnknownDiscipline_5_Category_26",
        (5, 27) => "UnknownDiscipline_5_Category_27",
        (5, 28) => "UnknownDiscipline_5_Category_28",
        (5, 29) => "UnknownDiscipline_5_Category_29",
        (5, 30) => "UnknownDiscipline_5_Category_30",
        (6, 0) => "UnknownDiscipline_6_Category_0",
        (6, 1) => "UnknownDiscipline_6_Category_1",
        (6, 2) => "UnknownDiscipline_6_Category_2",
        (6, 3) => "UnknownDiscipline_6_Category_3",
        (6, 4) => "UnknownDiscipline_6_Category_4",
        (6, 5) => "UnknownDiscipline_6_Category_5",
        (6, 6) => "UnknownDiscipline_6_Category_6",
        (6, 7) => "UnknownDiscipline_6_Category_7",
        (6, 8) => "UnknownDiscipline_6_Category_8",
        (6, 9) => "UnknownDiscipline_6_Category_9",
        (6, 10) => "UnknownDiscipline_6_Category_10",
        (6, 11) => "UnknownDiscipline_6_Category_11",
        (6, 12) => "UnknownDiscipline_6_Category_12",
        (6, 13) => "UnknownDiscipline_6_Category_13",
        (6, 14) => "UnknownDiscipline_6_Category_14",
        (6, 15) => "UnknownDiscipline_6_Category_15",
        (6, 16) => "UnknownDiscipline_6_Category_16",
        (6, 17) => "UnknownDiscipline_6_Category_17",
        (6, 18) => "UnknownDiscipline_6_Category_18",
        (6, 19) => "UnknownDiscipline_6_Category_19",
        (6, 20) => "UnknownDiscipline_6_Category_20",
        (6, 21) => "UnknownDiscipline_6_Category_21",
        (6, 22) => "UnknownDiscipline_6_Category_22",
        (6, 23) => "UnknownDiscipline_6_Category_23",
        (6, 24) => "UnknownDiscipline_6_Category_24",
        (6, 25) => "UnknownDiscipline_6_Category_25",
        (6, 26) => "UnknownDiscipline_6_Category_26",
        (6, 27) => "UnknownDiscipline_6_Category_27",
        (6, 28) => "UnknownDiscipline_6_Category_28",
        (6, 29) => "UnknownDiscipline_6_Category_29",
        (6, 30) => "UnknownDiscipline_6_Category_30",
        (7, 0) => "UnknownDiscipline_7_Category_0",
        (7, 1) => "UnknownDiscipline_7_Category_1",
        (7, 2) => "UnknownDiscipline_7_Category_2",
        (7, 3) => "UnknownDiscipline_7_Category_3",
        (7, 4) => "UnknownDiscipline_7_Category_4",
        (7, 5) => "UnknownDiscipline_7_Category_5",
        (7, 6) => "UnknownDiscipline_7_Category_6",
        (7, 7) => "UnknownDiscipline_7_Category_7",
        (7, 8) => "UnknownDiscipline_7_Category_8",
        (7, 9) => "UnknownDiscipline_7_Category_9",
        (7, 10) => "UnknownDiscipline_7_Category_10",
        (7, 11) => "UnknownDiscipline_7_Category_11",
        (7, 12) => "UnknownDiscipline_7_Category_12",
        (7, 13) => "UnknownDiscipline_7_Category_13",
        (7, 14) => "UnknownDiscipline_7_Category_14",
        (7, 15) => "UnknownDiscipline_7_Category_15",
        (7, 16) => "UnknownDiscipline_7_Category_16",
        (7, 17) => "UnknownDiscipline_7_Category_17",
        (7, 18) => "UnknownDiscipline_7_Category_18",
        (7, 19) => "UnknownDiscipline_7_Category_19",
        (7, 20) => "UnknownDiscipline_7_Category_20",
        (7, 21) => "UnknownDiscipline_7_Category_21",
        (7, 22) => "UnknownDiscipline_7_Category_22",
        (7, 23) => "UnknownDiscipline_7_Category_23",
        (7, 24) => "UnknownDiscipline_7_Category_24",
        (7, 25) => "UnknownDiscipline_7_Category_25",
        (7, 26) => "UnknownDiscipline_7_Category_26",
        (7, 27) => "UnknownDiscipline_7_Category_27",
        (7, 28) => "UnknownDiscipline_7_Category_28",
        (7, 29) => "UnknownDiscipline_7_Category_29",
        (7, 30) => "UnknownDiscipline_7_Category_30",
        (8, 0) => "UnknownDiscipline_8_Category_0",
        (8, 1) => "UnknownDiscipline_8_Category_1",
        (8, 2) => "UnknownDiscipline_8_Category_2",
        (8, 3) => "UnknownDiscipline_8_Category_3",
        (8, 4) => "UnknownDiscipline_8_Category_4",
        (8, 5) => "UnknownDiscipline_8_Category_5",
        (8, 6) => "UnknownDiscipline_8_Category_6",
        (8, 7) => "UnknownDiscipline_8_Category_7",
        (8, 8) => "UnknownDiscipline_8_Category_8",
        (8, 9) => "UnknownDiscipline_8_Category_9",
        (8, 10) => "UnknownDiscipline_8_Category_10",
        (8, 11) => "UnknownDiscipline_8_Category_11",
        (8, 12) => "UnknownDiscipline_8_Category_12",
        (8, 13) => "UnknownDiscipline_8_Category_13",
        (8, 14) => "UnknownDiscipline_8_Category_14",
        (8, 15) => "UnknownDiscipline_8_Category_15",
        (8, 16) => "UnknownDiscipline_8_Category_16",
        (8, 17) => "UnknownDiscipline_8_Category_17",
        (8, 18) => "UnknownDiscipline_8_Category_18",
        (8, 19) => "UnknownDiscipline_8_Category_19",
        (8, 20) => "UnknownDiscipline_8_Category_20",
        (8, 21) => "UnknownDiscipline_8_Category_21",
        (8, 22) => "UnknownDiscipline_8_Category_22",
        (8, 23) => "UnknownDiscipline_8_Category_23",
        (8, 24) => "UnknownDiscipline_8_Category_24",
        (8, 25) => "UnknownDiscipline_8_Category_25",
        (8, 26) => "UnknownDiscipline_8_Category_26",
        (8, 27) => "UnknownDiscipline_8_Category_27",
        (8, 28) => "UnknownDiscipline_8_Category_28",
        (8, 29) => "UnknownDiscipline_8_Category_29",
        (8, 30) => "UnknownDiscipline_8_Category_30",
        (9, 0) => "UnknownDiscipline_9_Category_0",
        (9, 1) => "UnknownDiscipline_9_Category_1",
        (9, 2) => "UnknownDiscipline_9_Category_2",
        (9, 3) => "UnknownDiscipline_9_Category_3",
        (9, 4) => "UnknownDiscipline_9_Category_4",
        (9, 5) => "UnknownDiscipline_9_Category_5",
        (9, 6) => "UnknownDiscipline_9_Category_6",
        (9, 7) => "UnknownDiscipline_9_Category_7",
        (9, 8) => "UnknownDiscipline_9_Category_8",
        (9, 9) => "UnknownDiscipline_9_Category_9",
        (9, 10) => "UnknownDiscipline_9_Category_10",
        (9, 11) => "UnknownDiscipline_9_Category_11",
        (9, 12) => "UnknownDiscipline_9_Category_12",
        (9, 13) => "UnknownDiscipline_9_Category_13",
        (9, 14) => "UnknownDiscipline_9_Category_14",
        (9, 15) => "UnknownDiscipline_9_Category_15",
        (9, 16) => "UnknownDiscipline_9_Category_16",
        (9, 17) => "UnknownDiscipline_9_Category_17",
        (9, 18) => "UnknownDiscipline_9_Category_18",
        (9, 19) => "UnknownDiscipline_9_Category_19",
        (9, 20) => "UnknownDiscipline_9_Category_20",
        (9, 21) => "UnknownDiscipline_9_Category_21",
        (9, 22) => "UnknownDiscipline_9_Category_22",
        (9, 23) => "UnknownDiscipline_9_Category_23",
        (9, 24) => "UnknownDiscipline_9_Category_24",
        (9, 25) => "UnknownDiscipline_9_Category_25",
        (9, 26) => "UnknownDiscipline_9_Category_26",
        (9, 27) => "UnknownDiscipline_9_Category_27",
        (9, 28) => "UnknownDiscipline_9_Category_28",
        (9, 29) => "UnknownDiscipline_9_Category_29",
        (9, 30) => "UnknownDiscipline_9_Category_30",
        (10, 0) => "Waves",
        (10, 1) => "Currents",
        (10, 2) => "Ice",
        (10, 3) => "Surface_Properties",
        (10, 4) => "Sub_surface_Properties",
        (_, c) => return format!("UnknownCategory_{c}"),
    })
    .to_string()
}

/// One entry of a GRIB2 parameter table: its name and its unit.
fn parameter(discipline: i32, category: i32, number: i32) -> Option<(&'static str, &'static str)> {
    Some(match (discipline, category, number) {
        (0, 0, 0) => ("Temperature", "K"),
        (0, 0, 1) => ("Virtual_temperature", "K"),
        (0, 0, 2) => ("Potential_temperature", "K"),
        (0, 0, 3) => ("Pseudo-adiabatic_potential_temperature", "K"),
        (0, 0, 4) => ("Maximum_temperature", "K"),
        (0, 0, 5) => ("Minimum_temperature", "K"),
        (0, 0, 6) => ("Dew_point_temperature", "K"),
        (0, 0, 7) => ("Dew_point_depression", "K"),
        (0, 0, 8) => ("Lapse_rate", "K.m-1"),
        (0, 0, 9) => ("Temperature_anomaly", "K"),
        (0, 0, 10) => ("Latent_heat_net_flux", "W.m-2"),
        (0, 0, 11) => ("Sensible_heat_net_flux", "W.m-2"),
        (0, 0, 12) => ("Heat_index", "K"),
        (0, 0, 13) => ("Wind_chill_factor", "K"),
        (0, 0, 14) => ("Minimum_dew_point_depression", "K"),
        (0, 0, 15) => ("Virtual_potential_temperature", "K"),
        (0, 0, 16) => ("Snow_phase_change_heat_flux", "W.m-2"),
        (0, 0, 17) => ("Skin_temperature", "K"),
        (0, 1, 0) => ("Specific_humidity", "kg.kg-1"),
        (0, 1, 1) => ("Relative_humidity", "percent"),
        (0, 1, 2) => ("Humidity_mixing_ratio", "kg.kg-1"),
        (0, 1, 3) => ("Precipitable_water", "kg.m-2"),
        (0, 1, 4) => ("Vapor_pressure", "Pa"),
        (0, 1, 5) => ("Saturation_deficit", "Pa"),
        (0, 1, 6) => ("Evaporation", "kg.m-2"),
        (0, 1, 7) => ("Precipitation_rate", "kg.m-2.s-1"),
        (0, 1, 8) => ("Total_precipitation", "kg.m-2"),
        (0, 1, 9) => ("Large_scale_precipitation", "kg.m-2"),
        (0, 1, 10) => ("Convective_precipitation", "kg.m-2"),
        (0, 1, 11) => ("Snow_depth", "m"),
        (0, 1, 12) => ("Snowfall_rate_water_equivalent", "kg.m-2.s-1"),
        (0, 1, 13) => ("Water_equivalent_of_accumulated_snow_depth", "kg.m-2"),
        (0, 1, 14) => ("Convective_snow", "kg.m-2"),
        (0, 1, 15) => ("Large_scale_snow", "kg.m-2"),
        (0, 1, 16) => ("Snow_melt", "kg.m-2"),
        (0, 1, 17) => ("Snow_age", "day"),
        (0, 1, 18) => ("Absolute_humidity", "kg.m-3"),
        (0, 1, 19) => ("Precipitation_type", ""),
        (0, 1, 20) => ("Integrated_liquid_water", "kg.m-2"),
        (0, 1, 21) => ("Condensate", "kg.kg-1"),
        (0, 1, 22) => ("Cloud_mixing_ratio", "kg.kg-1"),
        (0, 1, 23) => ("Ice_water_mixing_ratio", "kg.kg-1"),
        (0, 1, 24) => ("Rain_mixing_ratio", "kg.kg-1"),
        (0, 1, 25) => ("Snow_mixing_ratio", "kg.kg-1"),
        (0, 1, 26) => ("Horizontal_moisture_convergence", "kg.kg-1.s-1"),
        (0, 1, 27) => ("Maximum_relative_humidity", "percent"),
        (0, 1, 28) => ("Maximum_absolute_humidity", "kg.m-3"),
        (0, 1, 29) => ("Total_snowfall", "m"),
        (0, 1, 30) => ("Precipitable_water_category", ""),
        (0, 1, 31) => ("Hail", "m"),
        (0, 1, 32) => ("Graupel", "kg.kg-1"),
        (0, 1, 33) => ("Categorical_Rain", ""),
        (0, 1, 34) => ("Categorical_Freezing_Rain", ""),
        (0, 1, 35) => ("Categorical_Ice_Pellets", ""),
        (0, 1, 36) => ("Categorical_Snow", ""),
        (0, 1, 37) => ("Convective_Precipitation_Rate", "kg.m-2.s-1"),
        (0, 1, 38) => ("Horizontal_Moisture_Divergence", "kg.kg-1.s-1"),
        (0, 1, 39) => ("Percent_frozen_precipitation", "%"),
        (0, 1, 40) => ("Potential_Evaporation", "kg.m-2"),
        (0, 2, 0) => ("Wind_direction", "degrees"),
        (0, 2, 1) => ("Wind_speed", "m.s-1"),
        (0, 2, 2) => ("U-component_of_wind", "m.s-1"),
        (0, 2, 3) => ("V-component_of_wind", "m.s-1"),
        (0, 2, 4) => ("Stream_function", "m2.s-1"),
        (0, 2, 5) => ("Velocity_potential", "m2.s-1"),
        (0, 2, 6) => ("Montgomery_stream_function", "m2.s-2"),
        (0, 2, 7) => ("Sigma_coordinate_vertical_velocity", "s-1"),
        (0, 2, 8) => ("Vertical_velocity", "Pa.s-1"),
        (0, 2, 9) => ("Vertical_velocity", "m.s-1"),
        (0, 2, 10) => ("Absolute_vorticity", "s-1"),
        (0, 2, 11) => ("Absolute_divergence", "s-1"),
        (0, 2, 12) => ("Relative_vorticity", "s-1"),
        (0, 2, 13) => ("Relative_divergence", "s-1"),
        (0, 2, 14) => ("Potential_vorticity", "K.m2.kg-1.s-1"),
        (0, 2, 15) => ("Vertical_u-component_shear", "s-1"),
        (0, 2, 16) => ("Vertical_v-component_shear", "s-1"),
        (0, 2, 17) => ("Momentum_flux_u_component", "N.m-2"),
        (0, 2, 18) => ("Momentum_flux_v_component", "N.m-2"),
        (0, 2, 19) => ("Wind_mixing_energy", "J"),
        (0, 2, 20) => ("Boundary_layer_dissipation", "W.m-2"),
        (0, 2, 21) => ("Maximum_wind_speed", "m.s-1"),
        (0, 2, 22) => ("Wind_speed_gust", "m.s-1"),
        (0, 2, 23) => ("U-component_of_wind", "m.s-1"),
        (0, 2, 24) => ("V-component_of_wind", "m.s-1"),
        (0, 2, 25) => ("Vertical_speed_sheer", "s-1"),
        (0, 2, 26) => ("Horizontal_Momentum_Flux", "N.m-2"),
        (0, 2, 27) => ("U-Component_Storm_Motion", "m.s-1"),
        (0, 2, 28) => ("V-Component_Storm_Motion", "m.s-1"),
        (0, 2, 29) => ("Drag_Coefficient", ""),
        (0, 2, 30) => ("Frictional_Velocity", "m.s-1"),
        (0, 3, 0) => ("Pressure", "Pa"),
        (0, 3, 1) => ("Pressure_reduced_to_MSL", "Pa"),
        (0, 3, 2) => ("Pressure_tendency", "Pa.s-1"),
        (0, 3, 3) => ("ICAO_Standard_Atmosphere_Reference_Height", "m"),
        (0, 3, 4) => ("Geopotential", "m2.s-2"),
        (0, 3, 5) => ("Geopotential_height", "gpm"),
        (0, 3, 6) => ("Geometric_height", "m"),
        (0, 3, 7) => ("Standard_deviation_of_height", "m"),
        (0, 3, 8) => ("Pressure_anomaly", "Pa"),
        (0, 3, 9) => ("Geopotential_height_anomaly", "gpm"),
        (0, 3, 10) => ("Density", "kg.m-2"),
        (0, 3, 11) => ("Altimeter_setting", "Pa"),
        (0, 3, 12) => ("Thickness", "m"),
        (0, 3, 13) => ("Pressure_altitude", "m"),
        (0, 3, 14) => ("Density_altitude", "m"),
        (0, 3, 15) => ("N5-Wave_Geopotential_Height", "gpm"),
        (0, 3, 16) => ("Zonal_Flux_of_Gravity_Wave_Stress", "N.m-2"),
        (0, 3, 17) => ("Meridional_Flux_of_Gravity_Wave_Stress", "N.m-2"),
        (0, 3, 18) => ("Planetary_Boundary_Layer_Height", "m"),
        (0, 3, 19) => ("N5-Wave_Geopotential_Height_Anomaly", "gpm"),
        (0, 3, 20) => ("Standard_deviation_of_sub_grid_scale_orography", "m"),
        (0, 3, 21) => ("Angle_of_sub_grid_scale_orography", "Rad"),
        (0, 3, 22) => ("Slope_of_sub_grid_scale_orography", ""),
        (0, 3, 23) => ("Gravity_of_sub_grid_scale_orography", "W.m-2"),
        (0, 3, 24) => ("Anisotropy_of_sub_grid_scale_orography", ""),
        (0, 4, 0) => ("Net_short-wave_radiation_flux", "W.m-2"),
        (0, 4, 1) => ("Net_short-wave_radiation_flux", "W.m-2"),
        (0, 4, 2) => ("Short_wave_radiation_flux", "W.m-2"),
        (0, 4, 3) => ("Global_radiation_flux", "W.m-2"),
        (0, 4, 4) => ("Brightness_temperature", "K"),
        (0, 4, 5) => ("Radiance", "W.m-1.sr-1"),
        (0, 4, 6) => ("Radiance", "W.m-3.sr-1"),
        (0, 4, 7) => ("Downward_Short-Wave_Rad_Flux", "W.m-2"),
        (0, 4, 8) => ("Upward_Short-Wave_Rad_Flux", "W.m-2"),
        (0, 4, 9) => ("Net_short_wave_radiation_flux", "W.m-2"),
        (0, 4, 10) => ("Photosynthetically_active_radiation", "W.m-2"),
        (0, 4, 11) => ("Net_short_wave_radiation_flux_clear_sky", "W.m-2"),
        (0, 4, 12) => ("Downward_UV_radiation", "W.m-2"),
        (0, 5, 0) => ("Net_long_wave_radiation_flux", "W.m-2"),
        (0, 5, 1) => ("Net_long_wave_radiation_flux", "W.m-2"),
        (0, 5, 2) => ("Long_wave_radiation_flux", "W.m-2"),
        (0, 5, 3) => ("Downward_Long-Wave_Rad_Flux", "W.m-2"),
        (0, 5, 4) => ("Upward_Long-Wave_Rad_Flux", "W.m-2"),
        (0, 5, 5) => ("Net_long_wave_radiation_flux", "W.m-2"),
        (0, 5, 6) => ("Net_long_wave_radiation_flux_clear_sky", "W.m-2"),
        (0, 6, 0) => ("Cloud_Ice", "kg.m-2"),
        (0, 6, 1) => ("Total_cloud_cover", "percent"),
        (0, 6, 2) => ("Convective_cloud_cover", "percent"),
        (0, 6, 3) => ("Low_cloud_cover", "percent"),
        (0, 6, 4) => ("Medium_cloud_cover", "percent"),
        (0, 6, 5) => ("High_cloud_cover", "percent"),
        (0, 6, 6) => ("Cloud_water", "kg.m-2"),
        (0, 6, 7) => ("Cloud_amount", "percent"),
        (0, 6, 8) => ("Cloud_type", ""),
        (0, 6, 9) => ("Thunderstorm_maximum_tops", "m"),
        (0, 6, 10) => ("Thunderstorm_coverage", ""),
        (0, 6, 11) => ("Cloud_base", "m"),
        (0, 6, 12) => ("Cloud_top", "m"),
        (0, 6, 13) => ("Ceiling", "m"),
        (0, 6, 14) => ("Non-Convective_Cloud_Cover", "%"),
        (0, 6, 15) => ("Cloud_Work_Function", "J.kg-1"),
        (0, 6, 16) => ("Convective_Cloud_Efficiency", ""),
        (0, 6, 17) => ("Total_Condensate", "kg.kg-1"),
        (0, 6, 18) => ("Total_Column-Integrated_Cloud_Water", "kg.m-2"),
        (0, 6, 19) => ("Total_Column-Integrated_Cloud_Ice", "kg.m-2"),
        (0, 6, 20) => ("Total_Column-Integrated_Condensate", "kg.m-2"),
        (0, 6, 21) => ("Ice_fraction_of_total_condensate", ""),
        (0, 6, 22) => ("Cloud_cover", "%"),
        (0, 6, 23) => ("Cloud_ice_mixing_ratio", "kg.kg-1"),
        (0, 6, 24) => ("Sunshine", ""),
        (0, 6, 25) => ("Horizontal_extent_of_cumulonimbus", "percent"),
        (0, 7, 0) => ("Parcel_lifted_index", "K"),
        (0, 7, 1) => ("Best_lifted_index", "K"),
        (0, 7, 2) => ("K_index", "K"),
        (0, 7, 3) => ("KO_index", "K"),
        (0, 7, 4) => ("Total_totals_index", "K"),
        (0, 7, 5) => ("Sweat_index", ""),
        (0, 7, 6) => ("Convective_available_potential_energy", "J.kg-1"),
        (0, 7, 7) => ("Convective_inhibition", "J.kg-1"),
        (0, 7, 8) => ("Storm_relative_helicity", "J.kg-1"),
        (0, 7, 9) => ("Energy_helicity_index", ""),
        (0, 7, 10) => ("Surface_Lifted_Index", "K"),
        (0, 7, 11) => ("Best_lifted_index", "K"),
        (0, 7, 12) => ("Richardson_Number", ""),
        (10, 0, 0) => ("Wave_spectra_1", ""),
        (10, 0, 1) => ("Wave_spectra_2", ""),
        (10, 0, 2) => ("Wave_spectra_3", ""),
        (10, 0, 3) => ("Significant_height_of_combined_wind_waves_and_swell", "m"),
        (10, 0, 4) => ("Direction_of_wind_waves", "degrees"),
        (10, 0, 5) => ("Significant_height_of_wind_waves", "m"),
        (10, 0, 6) => ("Mean_period_of_wind_waves", "s"),
        (10, 0, 7) => ("Direction_of_swell_waves", "degrees"),
        (10, 0, 8) => ("Significant_height_of_swell_waves", "m"),
        (10, 0, 9) => ("Mean_period_of_swell_waves", "s"),
        (10, 0, 10) => ("Primary_wave_direction", "degrees"),
        (10, 0, 11) => ("Primary_wave_mean_period", "s"),
        (10, 0, 12) => ("Secondary_wave_direction", "degrees"),
        (10, 0, 13) => ("Secondary_wave_mean_period", "s"),
        (10, 1, 0) => ("Current_direction", "degrees"),
        (10, 1, 1) => ("Current_speed", "m.s-1"),
        (10, 1, 2) => ("U_component_of_current", "m.s-1"),
        (10, 1, 3) => ("V_component_of_current", "m.s-1"),
        (10, 2, 0) => ("Ice_cover", ""),
        (10, 2, 1) => ("Ice_thickness", "m"),
        (10, 2, 2) => ("Direction_of_ice_drift", "degrees"),
        (10, 2, 3) => ("Speed_of_ice_drift", "m.s-1"),
        (10, 2, 4) => ("U_component_of_ice_drift", "m.s-1"),
        (10, 2, 5) => ("V_component_of_ice_drift", "m.s-1"),
        (10, 2, 6) => ("Ice_growth_rate", "m.s-1"),
        (10, 2, 7) => ("Ice_divergence", "s-1"),
        (10, 2, 8) => ("Ice_temperature", "K"),
        (10, 3, 0) => ("Water_temperature", "K"),
        (10, 3, 1) => ("Deviation_of_sea_level_from_mean", "m"),
        (10, 4, 0) => ("Main_thermocline_depth", "m"),
        (10, 4, 1) => ("Main_thermocline_anomaly", "m"),
        (10, 4, 2) => ("Transient_thermocline_depth", "m"),
        (10, 4, 3) => ("Salinity", "kg.kg-1"),
        (10, 4, 4) => ("Meridional_overturning_circulation", "m3.s"),
        _ => return None,
    })
}

/// `ParameterTable.getParameterName(discipline, category, number)`.
pub fn parameter_name(discipline: i32, category: i32, number: i32) -> String {
    match parameter(discipline, category, number) {
        Some((name, _)) => name.to_string(),
        None => format!("UnknownParameter_D{discipline}_C{category}_{number}"),
    }
}

/// `ParameterTable.getParameterUnit(discipline, category, number)`.
pub fn parameter_unit(discipline: i32, category: i32, number: i32) -> String {
    match parameter(discipline, category, number) {
        Some((_, unit)) => unit.to_string(),
        None => UNKNOWN.to_string(),
    }
}
